image: hashicorp/terraform:full

stages:
  - test

test_auto_update:
  stage: test
  script:
    - apk update
    - apk upgrade
    - apk add --no-cache bash git grep coreutils curl
    - curl -Lo /usr/local/bin/terraform-docs "https://github.com/$(curl -s https://github.com/segmentio/terraform-docs/releases | grep terraform-docs-v0.6.0-linux-amd | head -n 1 | cut -d '"' -f 2)"
    - chmod +x /usr/local/bin/terraform-docs
    - ./scripts/ci.sh
    - git status
    - git diff --exit-code
  tags:
    - default
